language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only:
    - master
    - /^release-.*$/
matrix:
  allow_failures:
  - julia: nightly
after_success:
- julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
